theme: minima
title: daudi's
author: David Mwebaza
email: david.a.mwebaza@gmail.com
description: work/personal-ish blog
minima:
  social_links:
    - github: https://github.com/daud1
    - linkedin: https://linkedin.com/in/david-mwebaza
